services:
  - name: bert-fastapi
    type: web
    env: python
    region: oregon  # Choose your preferred region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    runtime: python3
